### PR TITLE
Add option to compute region-gene distance relative to TSS instead of gene body

### PR DESCRIPTION
**Pull request by schae211**
If I understand the code correctly, the distances of regions (putative enhancers) to genes are computed relative to the gene body. Given that the enhancer must interact with the promoter, one could also add a parameter to the "get_search_space" function to compute these distances relative to the TSS.
I created the pull request to show more clearly what I mean.

### CODE REVIEW

**Comment by SeppeDeWinter** [comment]
Hi @schae211 

Thank you for your contribution.

First of all, this function is not only used to calculate the distance from regions to genes but also to define a search space for each genes.

This search space is a space surrounding each gene from which ATAC-seq peaks are considered as potential enhancers regulating that gene.

By default we define this search space as 150 kb upstream of the start the gene, 150 kb downstream of the gene and all of the gene's introns.

Finally we calculate the distance from regions to genes by taking the minimum between a. the distance from the region to the start of the gene (the TSS) and b. the distance from the region to the end of the gene. This distance is reported for informational purposes only, but is not used internally.

With your change the definition of the search space would change (by default it would be 150 kb upstream and downstream of the TSS, which will also include exons). This is potentially not what you want.

Could you clarify why you would want to make this change? Do you want to change how the search space for each gene is calculated (and thus change which regions are considered as potential enhancers) or do you just want to calculated the distance from each potential enhancer to the TSS of the gene (instead of to the TSS or the end of the gene) but not change the search space?

Thanks,

Seppe

**Comment by schae211** [comment]
My intention would indeed be to change the definition of the search space for each gene (or at least to offer the possibility to do that).
I am using a search space of 250 kb in each direction, and with the current definition I get very large peak-TSS distance for some long genes (distances above 500 kb). DNA looping between the promoter (TSS) and a cis-regulatory element over those distances are biologically rather implausible I think.

**Comment by SeppeDeWinter** [comment]
I see!

With the current code you can already achieve something similar by setting `downstream` to `downstream=[0, 0]` and `upstream` to `upstream=[1000, 250000]`. Using this your search space will include 250 kb upstream of the TSS (taking into accounted the strandedness of the gene) and all the introns of the gene. 

I can see how longer genes creating a bias for longer distances can be a worry indeed. Another solution could be to add a parameter to specify the maximum distance from the TSS or maximum size of the search space. 

As to why we choose the number 150 kb specifically, this is indeed quite arbitrary so feel free to change it. In our hands (on all the human/mouse datasets we have run SCENIC+) 150 kb seems to work quite well. Also, from HiC data we have seen that most contacts happen within this window.

**Comment by schae211** [comment]
Okay thanks a lot for the discussion and explanation :)

**Pull request closed without merging**
